...
containers:
- name: weather-frontend
  image: weather-frontend:1.0
  imagePullPolicy: Always
  env:
  - name: BACKEND_HOSTPORT
    value: istio-ingressgateway.istio-system
  ports:
  - containerPort: 5000
...